# Generated by Django 2.2 on 2021-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_question_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posttype',
            field=models.IntegerField(default=0),
        ),
    ]
