# Generated by Django 2.2 on 2021-09-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_question_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='posttype',
            field=models.IntegerField(choices=[(0, '자유'), (1, '파이썬'), (2, '자바')], default=0),
        ),
    ]
